#!/bin/bash

read -p "Enter a number: " n
 origin=$n
 sum=0
 while (( n > 0)); do 
 temp=$((n%10))
 sum=$((sum+temp*temp*temp))
 n=$((n/10))
 done
 if ((origin == sum)); then
 echo "$origin is an Armstrong number."
 else
 echo "$origin is not an Armstrong number."
 fi
