#!/bin/bash

decimal_to_binary() {
  decimal=$1
  binary=""

  while [ $decimal -gt 0 ]; do
    remainder=$((decimal % 2))
    binary="$remainder$binary"
    decimal=$((decimal / 2))
  done

  echo "Binary representation: $binary"
}

read -p "Enter a decimal number: " number
decimal_to_binary $number
